import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1
  },
  backgroundImage: {
    resizeMode: "stretch", // or 'stretch'
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    flex: 1
  },
  loginForm: {},
  buttonStyle: {
    padding: 10,
    height: 45,
    overflow: "hidden",
    borderRadius: 1,
    backgroundColor: "orange",
    marginBottom: 5,
    marginRight: 5,
    marginLeft: 5,
    width: 250,
  },
  buttonStylePole: {
    padding: 10,
    height: 45,
    overflow: "hidden",
    borderRadius: 1,
    backgroundColor: "orange",
    top:-20,
    marginBottom: 5,
    marginRight: 5,
    marginLeft: 5,
    width: 250,
  },
  buttonAgs: {
    padding: 13,
    top: 4,
    height: 30,
    overflow: "hidden",
    borderRadius: 1,
    backgroundColor: "orange",
    marginBottom: 25,
    marginRight: 5,
    marginLeft: 6,
    width: 20,
  },
  buttonStylePnew: {
    padding: 10,
    height: 45,
    overflow: "hidden",
    borderRadius: 1,
    backgroundColor: "orange",
    marginBottom: 5,
    marginRight: 5,
    marginLeft: 60,
    top:-35,
    width: 40,
  },
   buttonStylePnew1: {
    padding: 10,
    height: 45,
    overflow: "hidden",
    borderRadius: 1,
    backgroundColor: "orange",
    marginBottom: 5,
    marginRight: 5,
    marginLeft: 5,
    top:-35,
    width: 40,
  },
  buttonStyleTextPnew: { 
  fontSize: 40, 
  color: "white",
  alignItems:"center",
  top: -18,
  },
  buttonStyleText: { fontSize: 18, color: "white" },
  inputStyle:{
    padding:10,
    backgroundColor:"blue",
    height:40,
    width:250,
    color:'#ffffff',
    marginBottom : 20,
    borderRadius:15,
  },
  inputStyle1:{
    padding:10,
    backgroundColor:"#ffffff",
    height:40,
    width:250,
    color:'#303030',
    marginBottom : 20,
    borderRadius:15,
  },
  
  pickerStyle:{
    backgroundColor:"white",
    color:"black",
    position: 'relative',
    top: -15,
    width: 250,
    height: 50,
  },
   pickerStylePnew:{
    backgroundColor:"white",
    color:"black",
    position: 'relative',
    top: -35,
    width: 40,
    height: 50,
    //marginBottom:20,
    marginRight:-50,
    marginLeft:20,
  },
  pickerStylePnew1:{
    backgroundColor:"white",
    color:"black",
    position: 'relative',
    top: -35,
    width: 40,
    height: 50,
    //marginBottom:20,
    marginRight:-50,
    marginLeft:60,
  },
  backButtonStyle:{
       justifyContent: 'space-between',
       color:"white",
       padding: 10,
    height: 45,
    overflow: "hidden",
    borderRadius: 1,
    width: 200,
  },
  backButtonStylePole:{
       justifyContent: 'space-between',
       color:"white",
       top: -22,
       padding: 10,
    height: 45,
    overflow: "hidden",
    borderRadius: 1,
    width: 200,
  },
  doneButtonStyle:{
    justifyContent: 'flex-end',
    alignItems:'flex-end',
    flexDirection:'column-reverse',    
  },
  textStyle: {
    marginTop: 20,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
    position: 'relative',
    top: -50,
    width: 250,
    height: 50,
 },
 textStylePole: {
    marginTop: 20,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
    position: 'relative',
    top: 20,
    width: 250,
    height: 50,
 },
 textStylePole1: {
    marginTop: 20,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
    position: 'relative',
    top: -10,
    width: 250,
    height: 50,
    marginLeft:20,
    marginRight:-30,

 },
 textStyleCruise: {
    marginTop: 20,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
    position: 'relative',
    top: -30,
    width: 250,
    height: 50,
 },
 textStyle1:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  top: 50,
  width:70,
  height:30,
 },
  textStyle1Pole:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 10,
  position: 'relative',
  top: 30,
  width:75,
  height:30,
 },
 textStyle3:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  top:30,
  width:90,
  height:50,
 },
 textStyleOrganic:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  top:30,
  width:83,
  height:50,
 },
 textStyleCanopy:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 15,
  position: 'relative',
  top:30,
  width:70,
  height:50,
 },
 textStyle2:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  width:80,
  height:30,
   top:-20,
  //marginRight:5,
 // marginLeft:-110,
  marginBottom : 5,
  //marginTop : 5,
 },
 textStyle4:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 15,
  position: 'relative',
  width:250,
  height:30,
  top:40,
 },
 textStyle5:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  width:60,
  height:30,
  top:20,
 },
 textStyleAdd:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  width:250,
  height:30,
  top:20,
 },
 textStyleNum:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 20,
  position: 'relative',
  width:80,
  height:30,
   top:-10,
   marginBottom:10,
 },
 btmbuttonStyle:{  
  padding: 10,
  height: 45,
  overflow: "hidden",
  borderRadius: 1,
  backgroundColor: "orange",
  marginBottom: 10,
  width: 250,  
 },
 rowSpeciesStyle:{
  flex: 1,
  flexDirection: 'row',
  justifyContent: 'center',
  alignItems:'center',
 },
 rowSpeciesStyle1:{

  flexDirection: 'row',
  justifyContent: 'space-between',//center
  alignItems:'center',
 },
 colSpeciesStyle:{
  flex: 1,
  flexDirection: 'column',
  justifyContent: 'space-between',
  alignItems:'center',
},
 inputSpeciesStyle:{
  padding:2,
  backgroundColor:"blue",
  height:30,
  width:50,
  color:'#ffffff',
  marginRight:15,
  marginLeft:20,
  marginBottom : 5,
  marginTop : 5,
  alignItems: "center",
  justifyContent: "center",
  top:-20,
},
inputSpeciesStyle1:{
  padding:2,
  backgroundColor:"blue",
  height:30,
  width:70,
  color:'#ffffff',
  marginRight:20,
  marginLeft:20,
  marginBottom : 5,
  marginTop : 5,
  alignItems: "center",
  justifyContent: "center",
   top:-20,
},
inputAgsStyle:{
padding:10,
  backgroundColor:"blue",
  top: 1,
  height:34,
  width:60,
  color:'#ffffff',
  marginRight:5,
  marginLeft:10,
  marginBottom : 25,
  marginTop : 5,
  alignItems: "center",
  justifyContent: "center",
},
inputAgsStyleOrganic:{
padding:2,
  backgroundColor:"blue",
  top: 1,
  height:30,
  width:65,
  color:'#ffffff',
  marginRight:8,
  marginLeft:10,
  marginBottom : 25,
  marginTop : 5,
  alignItems: "center",
  justifyContent: "center",
},
inputAgsStyleCanopy:{
padding:2,
  backgroundColor:"blue",
  top: 1,
  height:30,
  width:60,
  color:'#ffffff',
  marginRight:5,
  marginLeft:5,
  marginBottom : 25,
  marginTop : 5,
  alignItems: "center",
  justifyContent: "center",
},
inputaddsStyle:{
  padding:2,
  backgroundColor:"blue",
  height:40,
  width:230,
  color:'#ffffff',
  marginRight:5,
  marginLeft:15,
  marginBottom : 10,
  marginTop : 5,
  top:-10,
  alignItems: "center",
  justifyContent: "center",

},
textAgsStyle:{
  textAlign: 'center',
  color: 'white',
  fontWeight: 'bold',
  fontSize: 10,
  position: 'relative',
  width: 30,
  height: 30,
  padding:2,
  marginRight:5,
  marginLeft:5,
  marginBottom : 5,
  marginTop : 5,
},
textSpeciesStyle:{
  textAlign: 'center',
  color: '#ffffff',
  fontWeight: 'bold',
  fontSize: 16,
  position: 'relative',
  top:30,
  width:70,
  height: 30,
  //marginRight:5,
  marginLeft:5,
  marginBottom : 5,
  //marginTop : 5,
},
icon:{
  textAlign: 'center',
  color: '#ffffff',
  fontWeight: 'bold',
  fontSize: 50,
  position:"absolute",
  bottom :50,
  right :10,
}
});
